POST http://localhost:3003/partner
Content-Type: application/json

{
    "name": "Carlos Henrique",
    "lastname": "Rodrigues",
    "participation": 90
}


###
DELETE http://localhost:3003/partner/eef7ba87-9396-4d55-a347-790b0f5e9562


###
GET  http://localhost:3003/partners
